const likelist = [
    "Zero Two",
    "002",
    "Eo To",
    "Partner Killer",
    "The Horned Pistil Parasite",
    "Nine Iota",
    "9'ι",
    "9 Iota",
    "Rem",
    "Remrin",
    "Remrinrin",
    "Perfect Maid (RZ)",
    "Remririn",
    "Rem-lin",
    "The Sleeping Princess",
    "Perfect Little Sister Maid",
    "The All-Powerful Subordinate Maid and Younger Sister",
    "Natsuki Rem",
    "Rem Natsuki",
    "Megumin",
    "The True Crimson Goddess of Destruction",
    "Jailbait",
    "Crazy-Headed Girl",
    "The Top Mage in Axel",
    "Crazy Crimson Demon Girl",
    "The 'Incapable' Crimson Demon",
    "The Greatest of the Crimson Demons",
    "Crazy Exploding Girl",
    "Fake Megumin",
    "The Explosion Mage",
    "The Worst Mage",
    "The Joke Mage",
    "Loli Killer",
    "Eromin",
    "Onion Duck Murderer",
    "Explosion Artisan",
    "Meagermin",
    "Number One Joke Mage of the Crimson Demons",
    "Explosion Girl",
    "The #1 Explosion Fanatic of Axel",
    "Demon King Megumin",
    "Crimson Demon Megumin",
    "Duxion Slayer",
    "The Mad Exploder",
    "Ephemeral Existence",
    "Randoseru Girl",
    "Bunny Girl Senpai",
    "Mai Sakurajima",
    "Sakurajima Mai",
    "Rias Gremory",
    "Ria",
    "Crimson-Haired Ruin Princess",
    "Switch Princess",
    "Crimson Bust Princess",
    "Princess of Destruction",
    "Riia",
    "Hatsune Miku",
    "CV01",
    "Miku Hatsune",
    "Sakura Miku",
    "Snow Miku",
    "Racing Miku",
    "Symphony Miku",
    "Fluffy Coat Snow Miku",
    "Strawberry Daifuku Shiromuku Miku",
    "Magical Snow Snow Miku",
    "Snow Bell Snow Miku",
    "Snow Owl Snow Miku",
    "Twinkle Snow Snow Miku",
    "Crane Princess Snow Miku",
    "Snow Princess Snow Miku",
    "Snow Parade Snow Miku",
    "Glowing Snow Snow Miku",
    "The First Sound of the Future",
    "Ha2ne Miku",
    "Highnoone Miku",
    "Electronic Songstress",
    "Legendary Songstress",
    "Space Channel 39",
    "Miku-P",
    "Nightcord Miku",
    "Power",
    "Blood Fiend",
    "Blood Devil",
    "Powy",
    "Super Power",
    "Shit Devil",
    "Poop Devil",
    "The First President",
    "The Roommate Devil",
    "Satoru Gojou",
    "The Strongest Jujutsu Sorcerer",
    "Mr. Hotshot",
    "GTG",
    "Great Teacher Gojou",
    "The Pinnacle of the Jujutsu World",
    "The Greatest Sorcerer",
    "Master Gojo",
    "Satoru Gojo",
    "Gojo Satoru",
    "Gojou Satoru",
    "Saber",
    "Artoria Pendragon",
    "King of Knights",
    "Altria Pendragon",
    "King Arthur (F/SN)",
    "Blue Saber",
    "The King of Ghosts and Fairies",
    "Queen of Type Moon",
    "The Servant of the Sword",
    "King of Swords",
    "The Heroic Spirit of the Sword",
    "The King of Britain",
    "The True Guardian",
    "The Absolute Final Defense",
    "King of Chivalry",
    "Fleeting and Brilliant One",
    "The Undefeated King",
    "Saber Lily",
    "Artoria Pendragon (Lily)",
    "White Saber",
    "The Red Dragon That Protects Britain",
    "The King of Gluttony",
    "Saber Lion",
    "King of the Wild",
    "Proud Knight-King",
    "Dux Bellorum",
    "Once and Future King",
    "Arturia Pendragon",
    "Elise Watoson",
    "The King of the Beach",
    "Natural Born Pure White",
    "HMS Saber-01",
    "The God of War (F/SN)",
    "The King of Hungry",
    "Britain's Red Dragon",
    "The Ideal King",
    "Nezuko Kamado",
    "Minion 3",
    "Mghh-ko",
    "Nezuo",
    "Kamado Nezuko",
    "Chosen Demon",
    "Erabareshi Oni",
    "Nami",
    "Cat Burglar",
    "Namizo",
    "The Pirate Thief",
    "Na-chan (OP)",
    "O-Nami",
    "Namiland",
    "Namifia",
    "Nacchan (OP)",
    "Nami-swan",
    "Josephine, The Granddaughter of the Great Gold Pirate",
    "The Heathen Navigator",
    "Cat Burglar Nami",
    "The Cat Burglar",
    "Asuna",
    "Asuna Yuuki",
    "Queen Titania",
    "Yuuki Asuna",
    "Berserk Healer",
    "Stacia (SAO)",
    "Auna",
    "Erika (SAO)",
    "Aa-chan (SAO)",
    "Lightning Flash",
    "The Flash (SAO)",
    "Fierce Flash",
    "Knights of the Blood Sub-leader",
    "The Goddess of Creation Stacia",
    "Mikasa Ackerman",
  "Mikasa the Fighter",
  "Mikasa Ackermann",
  "Mikarin (AoT)",
  "Albedo",
  "Pure-White Devil",
  "The Merciful",
  "Ms. Over-the-Hill",
  "Guardian Overseer of the Great Underground Tomb of Nazarick",
  "Captain of the Great Tomb of Nazarick's Floor Guardians",
  "The Most Elite NPC in the Great Tomb of Nazarick",
  "Floor Guardian Captain",
  "Nazarick's Best Defender",
  "Captain of the Floor Guardians",
  "Makima",
  "Control Devil",
  "The Devil of Domination",
  "Monkey D. Luffy",
  "Straw Hat Luffy",
  "Mugiwara",
  "Straw Hat",
  "Lucy (OP)",
  "The Future Pirate King",
  "Gum-Gum",
  "Afro Luffy",
  "Hammer Boy",
  "Monkey Self-D. Isciplined Luffy",
  "Mugiwara no Luffy",
  "Luffyland",
  "Luffytaro",
  "Desert Doo-doo",
  "Booger Boy",
  "Luffy",
  "Rubber Monkey",
  "Water Luffy",
  "Giant Luffy Bomber",
  "Nightmare Luffy",
  "Straw-chan",
  "Rubber Guy",
  "Captain Luffy",
  "The 100 Million Berry Man",
  "Gum-Gum Human",
  "Straw-Hatted Lad",
  "Rubber Man (OP)",
  "Rubber Boss",
  "King Luffy",
  "The Star of Hope",
  "Party King (OP)",
  "Straw Fool",
  "Mugibaka",
  "Straw boy",
  "Luffy no Umi",
  "Straw (OP)",
  "Rubber Ball",
  "Big Bro Loo-Fee",
  "Rubber Boy (OP)",
  "Mr. Future-King-of-the-Pirates",
  "Chore Boy",
  "Shit-Hat",
  "King of the Balloons",
  "Gum-Gum Boy",
  "The Fifth Emperor",
  "Joyboy",
  "Nika, The Sun God",
  "The Fifth Emperor of the Sea",
  "Nico Robin",
  "Devil Child",
  "Miss All Sunday",
  "AllSunday",
  "Demon Child",
  "Light of the Revolution",
  "O-Robi",
  "Robiland",
  "Robiflowan",
  "Robin-chwan",
  "Mysterious Cool Beauty Nico Robin",
  "The Woman Who Draws Darkness",
  "Dobin-senpai",
  "Demon Child Nico Robin",
  "Nino Nakano",
  "Red (QQ)",
  "Nakano Nino",
  "Miku Nakano",
  "Nakano Miku",
  "Roronoa Zoro",
  "Pirate Hunter",
  "Marimo",
  "Moss-head",
  "One Eyed Ronin",
  "Mr. Bushido",
  "Moss-juro",
  "Cactus-kun",
  "Greenie (OP)",
  "Zoroland",
  "Sir Green",
  "Zorojuro",
  "Magistrate Cutter",
  "Zoro",
  "Roronoa Zolo",
  "Three-swords",
  "Zorokiller",
  "Haramaki",
  "Four-Sword Style",
  "The Wandering Swordsman",
  "The Fabled Pirate Hunter",
  "Roronoa The Swordsman",
  "Green Lettuce",
  "Shrub Head",
  "Cactus Head· Moss Head",
  "The King of Hell",
  "Demon-Slasher Zoro",
  "Sash-chan",
  "Zori",
  "Santōryū",
  "Cactus Boy",
  "The Demon Pirate Hunter",
  "Pirate Hunter Zoro",
  "Onigashima",
  "Green Kaido",
  "Green Mom",
  "Pirate Hunter Zolo",
  "Zolo the Pirate Hunter",
  "Zolo the Swordsman",
  "Itachi Uchiha",
  "Itachi of the Sharingan",
  "Clan Killer Itachi",
  "Prodigy of the Hidden Leaf Village",
  " Weasel (Naruto)",
  "Itachi Uchiha of the Leaf",
  "Uchiha Itachi",
  "Eren Jaeger",
  "Shingeki no Kyojin",
  "Suicidal Blockhead",
  "The Attack Titan",
  "Eren Yeager",
  "Eren Jäger",
  "Chee-burg Bastard",
  "Mr. Cheeseloaf",
  "The Woodwind O.G.",
  "The Cheeseloaf Dolt",
  "Artist Formerly Known as Putz",
  "Tulip Boy",
  "Mister Kruger",
  "The Founding Titan (Eren Jaeger)",
  "The War Hammer Titan (Eren Jaeger)",
  "The Usurper of the Founding Titan",
  "Ken Kaneki",
  "Nobara Kugisaki",
  "Kobeni Higashiyama",
  "Maki Zenin",
  "Erza Scarlet"
  
  ]; 
  
  
  module.exports = likelist;